### ISSUE TITLE
State of this code ?

### ISSUE THREAD

**Issue by ywmaa** [V-Sekai/many_bone_ik#22]
First of all, is this still maintained/being worked on ?

Secondly, is it planned to be merged into Godot Engine soon ?

Finally a suggestion, 
Can we convert it into GD extention or something for testing ?

**Comment by ywmaa** [comment]
> Can we convert it into GD extention or something for testing

Never mind, I think you did the right thing by having it as a module.

but what are the plans for merging or atleast opening a PR for this in the Godot Engine ?

**Comment by fire** [comment]
There is an old pr, but I am stuck designing a ui.

As far as I can tell people only to want to use IK for limbs and like the shoulder joint.

**Comment by ywmaa** [comment]
> There is an old pr, but I am stuck designing a ui.
> 
> As far as I can tell people only to want to use IK for limbs and like the shoulder joint.

Fullbody IK is something that is useful for full advanced animation, like the character applying leg IK while also trying to grab an object using the hands.

**Comment by perry-blueberry** [comment]
I also have a need for fullbody IK and would be interested in knowing the status.
1. Is there a plan to merge this at some point to Godot? Godot doesn't have a good IK solution currently as far as I can tell.
2. Is there any tutorial/documentation for how to get started with using this?
3. Is this at feature parity with the original EWBIK and have gone through some testing? I have tried the Processing Java thingy for that and it seemed to work quite well.

**Comment by fire** [comment]
I'm having trouble with stability of constrained humanoid rigs which is my blocker for merging into Godot Engine 4.3. It works for small bone sets.

For a Tutorial/Documentation, the base idea is you put a ManyBoneIK3D node beneath the skeleton and then add per bone constraint and target Node3Ds.

**Feature parity with the original EWBIK:** I think the original EWBIK is more stable when given the entire human skeleton.

I hope this helps! If you have any more questions or need further clarification, feel free to ask.

**Comment by fire** [comment]
I improved the many bone ik's implementation's stability.

# Remove Twist Current Ratio

Previously, the twist current ratio was saved as a property, leading to instability due to error accumulation. The new implementation removes this property.

# Non-Normalized Rotation

The system used to return an identity rotation for non-normalized rotations, causing abrupt movements. Now, rotations are normalized before use, ensuring smooth interpolation and stable behavior.

**Comment by fire** [comment]
The project is still active. I recently made a pr.
